### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by paulogdm** [paulogdm/micro-objection-realworld-example-app#1]
- [ ] Migrate to [micro-fork](https://github.com/amio/micro-fork)
- [ ] Apply [objection-db-errors](https://github.com/Vincit/objection-db-errors)
- [ ] Migrate to [now v2](https://zeit.co/blog/now-2).

Cheers!

**Comment by roelvan** [comment]
Great Repo! Looking forward to the implementation of Now v2 :)
